// export artists from "./artists"
// export artist from "./artist"
export championship from "./championship"
export teams from "./teams"
export team from "./team"
export players from "./players"
export table from "./table"
export fixtures from "./fixtures"
export teamfixtures from "./teamfixtures"
// export championships from "./championships"
